@DevJobsAPI_HostAddress = http://localhost:5130


GET {{DevJobsAPI_HostAddress}}/api/jobs/1
Accept: application/json


### ? Create a New Job (POST)
POST http://localhost:5130/api/jobs
Content-Type: application/json

{
    "title": ".NET Mid Software Engineer",
    "description": "Develop applications using C# and .NET",
    "company": "TechCorp",
    "location": "Sofia, Bulgaria",
    "minExperience": 2,
    "maxExperience": 5,
    "workMode": 3,
    "level": 3,
    "jobType": 2,
    "salary": 75000.00,
    "employerId": 1
}








PUT {{DevJobsAPI_HostAddress}}/api/jobs/1
Content-Type: application/json

{
    "id": 1,
    "title": "Senior Software Engineer",
    "description": "Lead software development projects",
    "company": "TechCorp",
    "location": "Hybrid",
    "minExperience": 4,
    "maxExperience": 8,
    "workMode": 2,
    "jobType": 1,
    "experienceLevel": 3,
    "salary": 95000,
    "employerId": 1
}


DELETE {{DevJobsAPI_HostAddress}}/api/jobs/1
Accept: application/json
